name: DISPATCH PRODUCTION - Build and Deploy

on:
  workflow_dispatch: {}
  push:
    branches: ["staging"]
    paths:
      - "dispatch/**"

env:
  PROJECT_ID: YOUR_GCP_PROJECT
  GAR_LOCATION: us-central1
  REPO: dispatch
  REGION: us-central1
  GKE_CLUSTER: production
  K8S_NAMESPACE: default

jobs:
  deploy:
    permissions: write-all

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.REGION }}

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build and Push Container
        env:
          IMAGE_TAG: "production-${{ github.sha }}"
        run: |-
          docker build \
            -f dispatch/Dockerfile \
            -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/$REPO:$IMAGE_TAG" \
            ./dispatch
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/$REPO:$IMAGE_TAG"

      - name: Deploy Secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
          sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg && \
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | \
          sudo tee /etc/apt/sources.list.d/1password.list && \
          sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/ && \
          curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
          sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol && \
          sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22 && \
          curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
          sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg && \
          sudo apt update && sudo apt install 1password-cli

          op user get --me

          scripts/op_to_yaml.py dispatch-production dispatch > new_secret.yaml
          kubectl apply -f new_secret.yaml -n "$K8S_NAMESPACE"

      - name: Deploy to GKE
        env:
          IMAGE_TAG: "production-${{ github.sha }}"
        run: |-
          kubectl set image deployment/dispatch dispatch="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/$REPO:$IMAGE_TAG" -n "$K8S_NAMESPACE"
          kubectl rollout status deployment/dispatch -n "$K8S_NAMESPACE"
          kubectl get services -o wide -n "$K8S_NAMESPACE"

      - name: Notify Slack on success
        if: ${{ success() }}
        env:
          IMAGE_TAG: "production-${{ github.sha }}"
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":tada: Dispatch deployed to production: \`$IMAGE_TAG\`\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: ${{ failure() }}
        env:
          GITHUB_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":warning: Dispatch production deployment failed: $GITHUB_RUN_URL\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
