#!/usr/bin/env node
/**
 * Generate braille Unicode art from an image file.
 *
 * Usage:
 *   npm run generate-logo -- path/to/logo.png
 *   npm run generate-logo -- path/to/logo.png --width 30 --threshold 128
 *
 * Outputs: lib/brand/logo-braille.ts
 *
 * Dependencies: sharp (added as devDependency)
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");

// ---------------------------------------------------------------------------
// Braille conversion
//
// Each braille character encodes a 2x4 grid of dots.
// Unicode braille starts at U+2800. Each dot maps to a bit:
//
//   (0,0)=0x01  (1,0)=0x08
//   (0,1)=0x02  (1,1)=0x10
//   (0,2)=0x04  (1,2)=0x20
//   (0,3)=0x40  (1,3)=0x80
// ---------------------------------------------------------------------------

const BRAILLE_BASE = 0x2800;
const DOT_MAP = [
  [0x01, 0x08],
  [0x02, 0x10],
  [0x04, 0x20],
  [0x40, 0x80],
];

function pixelsToBraille(grayscale, width, height, threshold) {
  const lines = [];

  for (let y = 0; y < height; y += 4) {
    let line = "";
    for (let x = 0; x < width; x += 2) {
      let code = 0;
      for (let dy = 0; dy < 4; dy++) {
        for (let dx = 0; dx < 2; dx++) {
          const px = x + dx;
          const py = y + dy;
          if (px < width && py < height) {
            const idx = py * width + px;
            // Dark pixels become dots (below threshold = dark)
            if (grayscale[idx] < threshold) {
              code |= DOT_MAP[dy][dx];
            }
          }
        }
      }
      line += String.fromCodePoint(BRAILLE_BASE + code);
    }
    lines.push(line);
  }

  // Trim trailing empty braille lines
  while (lines.length > 0 && lines[lines.length - 1].replace(/\u2800/g, "") === "") {
    lines.pop();
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function printUsage() {
  console.log(`
Usage: npm run generate-logo -- <image-path> [options]

Options:
  --width <n>      Output width in braille chars (default: 20)
  --threshold <n>  Brightness threshold 0-255 (default: 128)
  --invert         Invert colors (light dots on dark)
  --preview        Print preview only, don't write file

Examples:
  npm run generate-logo -- logo.png
  npm run generate-logo -- logo.png --width 30 --threshold 100
  npm run generate-logo -- favicon.svg --invert
`);
}

async function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    printUsage();
    process.exit(0);
  }

  // Parse args
  let imagePath = null;
  let brailleWidth = 20;
  let threshold = 128;
  let invert = false;
  let previewOnly = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--width" && args[i + 1]) {
      brailleWidth = parseInt(args[++i], 10);
    } else if (args[i] === "--threshold" && args[i + 1]) {
      threshold = parseInt(args[++i], 10);
    } else if (args[i] === "--invert") {
      invert = true;
    } else if (args[i] === "--preview") {
      previewOnly = true;
    } else if (!args[i].startsWith("-")) {
      imagePath = args[i];
    }
  }

  if (!imagePath) {
    console.error("Error: no image path provided");
    printUsage();
    process.exit(1);
  }

  // Dynamic import so the script fails gracefully if sharp isn't installed
  let sharp;
  try {
    sharp = (await import("sharp")).default;
  } catch {
    console.error(
      "Error: 'sharp' is not installed. Run: npm install --save-dev sharp"
    );
    process.exit(1);
  }

  const absPath = resolve(process.cwd(), imagePath);
  console.log(`Reading ${absPath}...`);

  // Each braille char is 2 pixels wide, so pixel width = brailleWidth * 2
  const pixelWidth = brailleWidth * 2;

  // Load and resize. sharp handles PNG, JPG, SVG, WebP, etc.
  const { data, info } = await sharp(absPath)
    .resize(pixelWidth, null, { fit: "inside" })
    .grayscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  if (invert) {
    for (let i = 0; i < data.length; i++) {
      data[i] = 255 - data[i];
    }
  }

  const braille = pixelsToBraille(data, info.width, info.height, threshold);

  // Preview
  console.log("\nPreview:\n");
  console.log(braille);
  console.log(`\nSize: ${info.width}x${info.height}px -> ${brailleWidth} chars wide`);

  if (previewOnly) {
    return;
  }

  // Write output file
  const outPath = resolve(PROJECT_ROOT, "lib/brand/logo-braille.ts");
  const escaped = braille.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  const content = `// Auto-generated by scripts/generate-logo.mjs
// Regenerate with: npm run generate-logo -- ${imagePath}

const DEFAULT_BRAILLE = \`${escaped}\`;

/**
 * Brand braille art displayed in the terminal header and welcome screen.
 *
 * Override via NEXT_PUBLIC_BRAND_BRAILLE env var, or regenerate from
 * your own logo with: npm run generate-logo -- path/to/logo.png
 */
export const BRAND_BRAILLE =
  process.env.NEXT_PUBLIC_BRAND_BRAILLE || DEFAULT_BRAILLE;
`;

  writeFileSync(outPath, content);
  console.log(`\nWrote ${outPath}`);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
