# Site-wide data
name: Chipp Docs
description: Documentation for the Chipp AI platform
github: https://github.com/BenchmarkAI/chipp-monorepo
twitter: https://twitter.com/chaborai
url: https://docs.chipp.ai
